### ISSUE TITLE
NPC names are random strings of characters

### ISSUE THREAD

**Issue by MrRar** [AiTechEye/xaenvironment#13]
I think the NPCs should have more natural looking names.

Here is an example of some good name generation code (MIT license): https://github.com/nyje/visual-bots/blob/48d80ce98a0ba3e576a220c4a9e8f91c1aef3574/init.lua#L21

**Comment by AiTechEye** [comment]
i made every second vowels and consonants, 1/3 of cases 2 of them, makes all kinds of names possible

https://github.com/AiTechEye/xaenvironment/commit/9c8a98a731c3ae5e3825ee669540654a9d88be6f

**Comment by MrRar** [comment]
It's definitely better now. However it does still result in unpronounceable names sometimes. I would recommend reducing the maximum length of names to reduce the chances of this happening. It also makes names more memorable if they're shorter.

**Comment by AiTechEye** [comment]
maximum length is now 8 instead of 12
