### ISSUE TITLE
A .blend file for every .b3d file

### ISSUE THREAD

**Issue by MrRar** [AiTechEye/xaenvironment#14]
Please upload .blend files for all .b3d files. examobs particularly has no .blend files available. That way anyone can modify and adapt the models. Otherwise it isn't really open source software.

The models you made are very nice by the way!

**Comment by AiTechEye** [comment]
I done that before, but this files took a lot of space so i had to remove them, i think it was like 200mb.
You can import them but the armatures will stop work and in newer blender versions it is a completely mess with it.

to work with minetest & blender 2.8+ is really wierd

**Comment by MrRar** [comment]
>I done that before, but this files took a lot of space so i had to remove them, i think it was like 200mb.

In that case store them in a separate repository. This is exactly what MineClone 2 does.

>You can import them but the armatures will stop work and in newer blender versions it is a completely mess with it.

Yes. This is why the .blend files are necessary.

> to work with minetest & blender animations 2.8+ is really wierd

Blender 2.93.5 is the latest version of Blender that works with io_scene_b3d that I know off.

**Comment by AiTechEye** [comment]
the problem is the blend files is gone

**Comment by MrRar** [comment]
Using various grep and git commands here is what I found out:


The repo has these .blend files now:

mods/exa2d/models/mt2d_character.blend
mods/player_style/models/character-blender-2.9.1.blend
mods/quads/models/quads_car.blend
mods/quads/models/quads_quad.blend


Missing .blend files:

mods/default/models/default_furnace.b3d
mods/examobs/models/examobs_beetle.b3d
mods/examobs/models/examobs_candycane.b3d
mods/examobs/models/examobs_crab.b3d
mods/examobs/models/examobs_fly.b3d
mods/examobs/models/examobs_gingerbread.b3d
mods/examobs/models/examobs_icecreamball.b3d
mods/examobs/models/examobs_icecreammaster.b3d
mods/examobs/models/examobs_lollipop.b3d
mods/examobs/models/examobs_pig.b3d
mods/examobs/models/examobs_shark.b3d
mods/examobs/models/examobs_spider.b3d
mods/examobs/models/examobs_tick.b3d
mods/examobs/models/examobs_wasp.b3d


Retreviable .blend files:

mods/air_balloons/models/air_balloons.blend ef2170fa70e94c1d6473d334c78c081ad5bc0910
mods/beds/models/tent.blend a6e923a0e5c76c9bc8564ac9ed1daf936ecf34be
mods/examobs/models/examobs_wolf.blend 8bc8b84a967d65d81bc6d33e1aea4744bc00c3f6
mods/examobs/models/examobs_tntbox.blend a36922384e90fd716f6c0e50c76100e72898288d
mods/examobs/models/examobs_titan.blend caef389457b004d34107d80b16fe839f5951a18e
mods/examobs/models/examobs_stonemonster.blend c6f31884e296e348ba5035f2bf5a4aa1250c9d2f
mods/examobs/models/examobs_skeleton.blend 5c23837b41a695b734cb075e0754fdb0e127e0f9
mods/examobs/models/examobs_sheep.blend f8f5999e3ba5c2214fb21f35b84b63a59e67e0ff
mods/examobs/models/examobs_mudmonster.blend ac172febff922f01bf39e9174936b59418a5460c
mods/examobs/models/examobs_mouse.blend 5d6ae0221a262ccdff5d087a6b4fe32b69d915fc
mods/examobs/models/examobs_fish.blend 601a4084b9e90dc23e04e4536880ecac5ff2c0d2
mods/examobs/models/examobs_duck.blend daa6ceb81dad7cab897b89b9e7dff906c6223cd3
mods/examobs/models/examobs_chicken.blend 6659d9ef28e04f9586d4660ac740083ebeeef8ab
mods/examobs/models/examobs_bird.blend 974c8bcf6388651d6640803fa402335363eb239a
mods/examobs/models/examobs_bear.blend 95300498b1eb17b8b30e76c9e59986fa15fe4596
mods/plasma/models/plasma_cannon.blend 936d4df40c67e5159d77a999dc048ac0a2e04951
mods/armor/models/armor_chestplate.blend 4c540c9c91afd4050f4ca9cfc023e53df9ed75e1
mods/plants/models/plants_cabbage.blend 278246731f106773e5fafde992e990ff9257af7a


I would definitely recommend creating a Blender file repository and putting all of them in that.

**Comment by AiTechEye** [comment]
i dont really know how git works, but this is cool, we does as you said and put them in a [new repository](https://github.com/AiTechEye/mesh_resources)

the candy monsters came from [here](https://github.com/AiTechEye/aliveai_candy) or [here](https://github.com/AiTechEye/aliveai)

**Comment by AiTechEye** [comment]
i found a old version of the spider and the candycane in the aliveai history.

added the downloadable blend [files](https://github.com/AiTechEye/mesh_resources)

**Comment by MrRar** [comment]
Here is my updated list of missing .blend files:
mods/default/models/default_furnace.b3d
mods/examobs/models/examobs_beetle.b3d
mods/examobs/models/examobs_crab.b3d
mods/examobs/models/examobs_fly.b3d
mods/examobs/models/examobs_gingerbread.b3d
mods/examobs/models/examobs_icecreamball.b3d
mods/examobs/models/examobs_icecreammaster.b3d
mods/examobs/models/examobs_lollipop.b3d
mods/examobs/models/examobs_pig.b3d
mods/examobs/models/examobs_shark.b3d
mods/examobs/models/examobs_tick.b3d
mods/examobs/models/examobs_wasp.b3d
