### ISSUE TITLE
Make craft guide node a menu in the inventory

### ISSUE THREAD

**Issue by MrRar** [AiTechEye/xaenvironment#16]
I tried playing a survival game in xaenvironment and I noticed a few issues. You start out with a craft guide node. But as soon as you die you have no idea how to make anything. Also it is kind of hard to use because you have to place it before you can access it. I think it would be much better to just have a menu in the inventory.

**Comment by AiTechEye** [comment]
i think i making a new clean one and replacing the other.
This is not easy cuz the current version can be included in other formspecs, have settings and can include recipes that are only able through the workbench.
And it is based on node meta, you cant change pages if it is not based on nodemeta

**Comment by MrRar** [comment]
This is very good.

I see two issues with it. One is that now the player starts out with two craft guides. I would recommend having new players not start with the craft guide node.

The other issue is that there is no visual indicator of which item is selected in the craft guide. When you press an item it shows the recipe but it does not show what the recipe is for.

**Comment by AiTechEye** [comment]
823d616 i replaced the grid image with the selected item

**Comment by AiTechEye** [comment]
it is solved, is works fine with craft guides and the workbench or any node where **player_style.craftguide.show(player,pos)** is called

**Comment by MrRar** [comment]
Awesome!
