### ISSUE TITLE
No swords in xaenvironment

### ISSUE THREAD

**Issue by MrRar** [AiTechEye/xaenvironment#20]
There are no swords in xaenvironment. It seems like an obvious omission. Maybe there is a reason for it? I think it would be nice to have swords to fight hostile mobs in the game.

**Comment by AiTechEye** [comment]
i didn't want swords or weapons, so i made vineyard knives instead, but then i still had to make weapons cuz the mobs became dangerous. axes and hoes works fine, so there is no need for swords.

**Comment by MrRar** [comment]
> axes and hoes works fine, so there is no need for swords.

Good to know. This is rather unobvious. Maybe the description of axes and hoes could say that they can be used as weapons or something. There needs to be some way of conveying that information to the user.

**Comment by AiTechEye** [comment]
i had a plan to add a guide on new worls, that shows arrows/tips and stuff in the inventory, i could include them in that.
the thing is, i want to make a story mode,  if you does /play_scene you can see the beginning of it, the only problem is i need the camera api to do it.

**Comment by MrRar** [comment]
> by the way, as i added you as a collaborator, now you can do changes without having to request?

In some cases you don't agree with my ideas so It might be better to ask first at least in some cases.

**Comment by AiTechEye** [comment]
9a8be1b fixed

**Comment by MrRar** [comment]
Nice. Now the damage will show in the tooltip.
