### ISSUE TITLE
Make basic materials more obtainable

### ISSUE THREAD

**Issue by MrRar** [AiTechEye/xaenvironment#21]
Some of the basic materials in the game are a little to rare in my opinion.

Flint - This is a material that is very basic and needed to bootstrap making tools and getting resources. It is like punching a tree in Minecraft or MTG. You have to dig sand under water. I think it should be a more common drop. You also need sticks but that is easy to get from tree leaves.

Iron Ore - This is a very useful material. You get it from caves. I think it should be more common. You can find plenty of oddstone and crystals but iron ore is kind of rare.

Coal - Same as above. Not quite as rare as iron ore but I wish it were more common.

**Comment by AiTechEye** [comment]
d7740eb

i just discovered, for some reason oddstone was overgenerated, those took the most space in the underground, there should be 80% less of them now.

- iron & coal is more common now
- you can craft leaves to sticks
- now you can find flint on beaches, max y=5 height
- added aluminium, crapy tools, but good as material

i'm working to add police stations in the cities, with police officers that can send you/objects to jail for 1-2 min (1 punch), the most is done. when you are detected as criminal all police officers will haunt you :)

**Comment by MrRar** [comment]
> i'm working to add police stations in the cities, with police officers that can send you/objects to jail for 1-2 min (1 punch), the most is done. when you are detected as criminal all police officers will haunt you :)

That sounds totally awesome! Things like that are why I like this game.

**Comment by AiTechEye** [comment]
the hard thing right now is to make the jails working with tech, right now it is a object detector, thats starts a timer, after them timeout it moves the floor (node switches) falling down ona teleport, moving out the object, the only problem if 8 of them can fit under the police station.

**Comment by MrRar** [comment]
I pulled the latest commits and created a new world. Now coal and iron are much more common. Great!

**Comment by MrRar** [comment]
> the hard thing right now is to make the jails working with tech, right now it is a object detector, thats starts a timer, after the timeout it moves the floor (node switches) falling down ona teleport, moving out the object, the only problem if 8 of them can fit under the police station.

I really don't know how the tech stuff works. It sounds cool though. Maybe I will play around with it and try to figure out how tech works. Do you have any tutorial or something?

**Comment by AiTechEye** [comment]
not yet, it works like mesecons, but instead of turning things on when the wire is on and off when the wire is off, this turns things on in one signal, and off in next signal. you can do really cool things with it.

usually when i am playing, im making a factory, that disassembles items, sorting and selling things automatically to make a lot of money
