### ISSUE TITLE
The breath bar is underneath other bars

### ISSUE THREAD

**Issue by luk3yx** [AiTechEye/xaenvironment#23]
The breath bar is currently at the bottom and there's an empty gap when it isn't visible:
![image](https://user-images.githubusercontent.com/3182651/211175129-9fad6b56-9a2a-46d3-84d0-42c1b038fab4.png)
![image](https://user-images.githubusercontent.com/3182651/211175135-7240ef20-b235-48f1-bd29-7efc1f504124.png)

The bar could be moved to the left-hand side (above the health bar) with the following code:

```lua
minetest.hud_replace_builtin("breath", {
	hud_elem_type = "statbar",
	position = {x = 0.5, y = 1},
	text = "bubble.png",
	text2 = "bubble_gone.png",
	number = minetest.PLAYER_MAX_BREATH_DEFAULT * 2,
	item = minetest.PLAYER_MAX_BREATH_DEFAULT * 2,
	size = {x = 24, y = 24},
	offset = {x = -265, y = -120},
})
```

**Comment by AiTechEye** [comment]
<img width="411" alt="screenshot_20230108_195538" src="https://user-images.githubusercontent.com/40591179/211213894-768836a8-fe9a-49d1-8850-97ec1a6e7cd9.png">

i am unsure.
but do we need a armour bar too?
