### ISSUE TITLE
Can't equip snowman hat

### ISSUE THREAD

**Issue by Wuzzy2** [AiTechEye/xaenvironment#26]
If you kill the snowman mob, it stops its hat. However, you can't equip the hat. I try to put it into the "Hats" slot but nothing happens.

The hat item shows "`examobs:hat`" in inventory.

ContentDB version: 2024-01-23

**Comment by AiTechEye** [comment]
yeah its not the same as the "real" top hat, and i dont really dont know what to do with it cuz the real one can teleport things and is expensive to do, this fake one cost nothing, do you think it should be possable to equip with it anyway?

**Comment by MrRar** [comment]
> yeah its not the same as the "real" top hat, and i dont really dont know what to do with it cuz the real one can teleport things and is expensive to do, this fake one cost nothing, do you think it should be possable to equip with it anyway?

Definitely yes.
