### ISSUE TITLE
Crash at start with MT 5.3.0

### ISSUE THREAD

**Issue by scribbler957** [AiTechEye/xaenvironment#3]
It crashes as soon as I start walking:
```
AsyncErr: environment_Step: Runtime error from mod 'player_style' in callback environment_Step(): .../minetest/games/xaenvironment/mods/player_style/init.lua:581: attempt to index local 'v' (a nil value)
stack traceback:
	.../minetest/games/xaenvironment/mods/player_style/init.lua:581: in function <.../minetest/games/xaenvironment/mods/player_style/init.lua:395>
	...inetest.app/Contents/Resources/builtin/game/register.lua:429: in function <...inetest.app/Contents/Resources/builtin/game/register.lua:413>
stack traceback:
```

**Comment by AiTechEye** [comment]
seems like you got XE 9.5, you need MT 5.4.0 to play it

you can download MT 5.4 here https://forum.minetest.net/viewtopic.php?f=42&t=17439
and you can download the current XE 9.99 here https://github.com/AiTechEye/xaenvironment
the XE 10 release will probability be same, just checking for bugs until mt 5.4 is released

anyway thanks for your bugreport
