### ISSUE TITLE
Eating food fills up your inventory (suggestion to make eating less wasteful)

### ISSUE THREAD

**Issue by Wuzzy2** [AiTechEye/xaenvironment#35]
## The problem

Eating lots of food can be very wasteful of inventory slots.

If you eat  at stack of food where you can take multiple "bites", the inventory quickly fills up.

Let's say you have a stack of 99 apples. You want to make 5 "bites". What this does is you eat from 5 different apples, moving 5 apples of which each of them was "bitten" only once to the other inventory slots.

This is very annoying because it quickly wastes your precious inventory slots.

## Suggestion

Make sure the player keeps eating from the same item. This could be done like this:

* First "bite": Put the single "bitten" apple into the wielded item slot, move the remaining 98 apples to the next free item slot. If there is no free item slot, drop the single apple on the floor instead (because it doesn't fit)
* Last "bite" (that uses up the apple): Look for the first stack of apples (or single apple) in the inventory and move it to the wielded slot. If there are no apples left, do nothing

## Version

ContentDB version: 2024-01-23

**Comment by MrRar** [comment]
I really like that idea!

**Comment by AiTechEye** [comment]
it sounds like it makes things less complicated 👍 which I hadn't a thought about
I dont know when i can start to do changes to the game cuz I just decided to take a much needed break from coding a while

**Comment by AiTechEye** [comment]
it was a stress issue, that i fixed in a odd way easrlier today
