### ISSUE TITLE
Placing the last block in the wielded slot triggers "dive roll"

### ISSUE THREAD

**Issue by Wuzzy2** [AiTechEye/xaenvironment#40]
If you place a block while walking forwards and it was the last block in your wielded inventory slot, you will do the "dive roll" parcours move. This ALWAYS comes unexpected and I don't know how often this accidental move has killed me lol.

ContentDB version: 2024-01-23

**Comment by AiTechEye** [comment]
it always happens when you walks forwards and right clicks with empty hand, but i added a limit so you dont rolling over nodes any more, it was using the original function for crawling & diving.
